version: "3.7"

services:
  web:
    build: .
    command: >
      sh -c  "python manage.py migrate --noinput &&
              python manage.py runserver 0.0.0.0:8000 &&
              gunicorn tubers.wsgi:application --bind=0.0.0.0:8000 "
    environment:
      DEBUG: 1
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - tubers_network

networks:
  tubers_network:
    driver: bridge
